sudo: required
servies:
  - docker

before_install:
  - docker build -t krsevan/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true krsevan/react-test npm test

after_success:
  - docker build -t krse22/multi-client ./client
  - docker build -t krse22/multi-nginx ./nginx
  - docker build -t krse22/multi-server ./server
  - docker build -t krse22/multi-worker ./worker
  # Log in to the docker CLI
  # - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password--stdin
  docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD"
  # Take those images and push them to docker hub
  # Extra comment 2
  - docker push krse22/multi-client
  - docker push krse22/multi-nginx
  - docker push krse22/multi-server
  - docker push krse22/multi-worker
