sudo: required
servies:
  - docker

before_install:
  - docker build -t krsevan/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true krsevan/react-test npm test

after_success:
  - docker build -t krse22/multi-client ./client
  - docker build -t krse22/multi-nginx ./nginx
  - docker build -t krse22/multi-server ./server
  - docker build -t krse22/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD"
  - docker push krse22/multi-client
  - docker push krse22/multi-nginx
  - docker push krse22/multi-server
  - docker push krse22/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-129262059706
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY